accelerate launch --config_file train_config/accelerate.yaml -m examples.wanvideo.model_training.train_with_accelerate \
  --model_config_path '/hpc2hdd/home/hongfeizhang/hongfei_workspace/DiffSynth-Studio/model_config/controlnet_config.yaml' \
  --training_state_dir '' \
  --height 480 \
  --width 720 \
  --output_path '/hpc2hdd/home/hongfeizhang/experiments/Wan/2025-07-31-14-14-1e-4' \
  --model_id_with_origin_paths "PAI/Wan2.1-Fun-V1.1-1.3B-InP:diffusion_pytorch_model*.safetensors,PAI/Wan2.1-Fun-V1.1-1.3B-InP:models_t5_umt5-xxl-enc-bf16.pth,PAI/Wan2.1-Fun-V1.1-1.3B-InP:Wan2.1_VAE.pth,PAI/Wan2.1-Fun-V1.1-1.3B-InP:models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth" \
  --learning_rate 1e-4 \
  --num_epochs 50 \
  --remove_prefix_in_ckpt "pipe.dit." \
  --trainable_models "dit" \
  --validate_step 200 \
  --use_gradient_checkpointing \
  --train_max_frame 61 \
  --train_min_frame 5 \
  --test_min_frame 29 \
  --no_extra_frame \
  --train_only_camera