accelerate launch --config_file train_config/accelerate_acc16.yaml -m examples.wanvideo.model_training.train_with_accelerate \
  --model_config_path '/hpc2hdd/home/hongfeizhang/hongfei_workspace/DiffSynth-Studio/model_config/controlnet_pre_pose.yaml' \
  --training_state_dir '' \
  --height 480 \
  --width 720 \
  --output_path '/hpc2hdd/home/hongfeizhang/experiments/Wan/2025-08-01-13-55-1e-4' \
  --model_id_with_origin_paths "PAI/Wan2.1-Fun-V1.1-1.3B-InP:diffusion_pytorch_model*.safetensors,PAI/Wan2.1-Fun-V1.1-1.3B-InP:models_t5_umt5-xxl-enc-bf16.pth,PAI/Wan2.1-Fun-V1.1-1.3B-InP:Wan2.1_VAE.pth,PAI/Wan2.1-Fun-V1.1-1.3B-InP:models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth" \
  --learning_rate 1e-4 \
  --num_epochs 1000 \
  --remove_prefix_in_ckpt "pipe.dit." \
  --trainable_models "dit" \
  --validate_step 100 \
  --use_gradient_checkpointing \
  --train_max_frame 41 \
  --train_min_frame 5 \
  --test_min_frame 17 \
  --no_extra_frame \
  --warmup_steps 500
